on: [push]

jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: build&deploy
        
        steps:
        # To use this repository's private action, you must check out the repository
            - name: Checkout
              uses: actions/checkout@v3.3.0

            - name: Install node modules
              run: yarn
              working-directory: private

            - name: Install composer stuff
              run: composer install --optimize-autoloader --no-dev
              working-directory: private

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.3.3
              with:
                server: jpsretail.nl
                username: jpsretail.nl
                password: ${{ secrets.ftp_password }}
                server-dir: backups/
                dry-run: true
                log-level: standard
